
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 13 00:03:28 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 22;
  public static final int CONST = 26;
  public static final int GREATEROREQUAL = 27;
  public static final int NUMCONST = 46;
  public static final int NOTEQUAL = 28;
  public static final int LPAREN = 11;
  public static final int GREATER = 30;
  public static final int SEMI = 9;
  public static final int CONTINUE = 29;
  public static final int COMMETN = 24;
  public static final int LESS = 31;
  public static final int FOR = 32;
  public static final int MINUS = 33;
  public static final int RPAREN = 12;
  public static final int AND = 16;
  public static final int OR = 17;
  public static final int COMMA = 10;
  public static final int CLASS = 34;
  public static final int INC = 19;
  public static final int DIV = 35;
  public static final int LESSOREQUAL = 15;
  public static final int PLUS = 7;
  public static final int ASSIGN = 18;
  public static final int IF = 4;
  public static final int DOT = 21;
  public static final int ABSTRACT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int RBRACKET = 23;
  public static final int EQUAL = 8;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 37;
  public static final int MOD = 38;
  public static final int IDENT = 44;
  public static final int BREAK = 39;
  public static final int VOID = 42;
  public static final int LBRACE = 13;
  public static final int ELSE = 3;
  public static final int READ = 41;
  public static final int CHARCONST = 45;
  public static final int RBRACE = 14;
  public static final int BOOLCONST = 43;
  public static final int EXTENDS = 40;
  public static final int PROG = 2;
  public static final int DEC = 20;
  public static final int PRINT = 5;
}

